config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticate :user, -> (user) { user.has_role?(:sysadmin) } do
    mount PgHero::Engine, at: "pghero"
  end

  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  root 'pages#welcome'

  get 'pages/terms_and_conditions'
  get 'pages/privacy_policy'
  get 'pages/cookie_policy'
  get 'pages/sitemap'
  get 'pages/public_statistics'
  get 'pages/cheat_sheet'

  get 'sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

  resources :users, only: [:show, :destroy] do
    put :toggle_theme, on: :member
  end

  resources :superadmins, only: [:new, :create]
  get '/superadmins', to: 'superadmins#new'

  resources :admins, only: [:new, :create]
  get '/admins', to: 'admins#new'

  resources :members, only: [:new, :create]
  get '/members', to: 'members#new'

  resources :visitors, only: [:new, :create]
  get '/visitors', to: 'visitors#new'

  resources :rooms do
    resources :notes, only: [:new, :create]
  end

  resources :articles do
    resources :comments, only: [:create, :destroy]
    scope module: :articles do
      resources :likes, only: [:create, :destroy]
    end
  end

  resources :todo_items, only: [:index]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # Todo Items
      resources :todo_items, only: [:index, :show, :create, :update, :destroy]
      # Articles
      resources :articles, only: [:index, :show, :create, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
      end
      # Rooms
      resources :rooms, only: [:index, :show, :create, :update, :destroy]
      # Charts
      namespace :charts do
        ## Analytics
        get 'month_of_year-visits'
        get 'month_of_year_visit-events'
        get 'device-type'
        get 'os-type'
        get 'browser-type'
        get 'landing-pages'
        get 'visit-mapping'
        get 'visit-country'
        get 'visit-region'
        get 'visit-city'
        get 'month_of_year_viewed_welcome'
        get 'month_of_year_viewed_dashboard'
        get 'month_of_year_viewed_blog'
        get 'month_of_year_viewed_rooms'
        get 'month_of_year_viewed_list'
        get 'month_of_year_viewed_article'
        get 'month_of_year_viewed_room'
        get 'month_of_year_viewed_user'
        get 'month_of_year_viewed_terms'
        get 'month_of_year_viewed_privacy-policy'
        get 'month_of_year_viewed_cookies-policy'
        get 'month_of_year_viewed_sitemap'
        get 'month_of_year_viewed_cheat-sheet'
        get 'month_of_year_viewed_public-statistics'
        # Users
        get 'month_of_year-superadmins'
        get 'month_of_year-admins'
        get 'month_of_year-members'
        get 'month_of_year-visitors'
        get 'month_of_year-users'
        get 'free_member-roles'
        get 'user-themes'
        get 'user-timezones'
        # Articles
        get 'article-likes'
        get 'month_of_year_article-likes'
        get 'month_of_year-articles'
        get 'month_of_year_single_articles'
        get 'free_member-articles'
        # Rooms
        get 'month_of_year-rooms'
        get 'month_of_year_single_rooms'
        get 'chat-rooms'
        # Todo Items
        get 'complete_incomplete-todos'
        get 'complete_incomplete_single-todos'
        get 'month_of_year-todos'
        get 'month_of_year_single-todos'
      end
    end
  end

end

app/models/article.rb
class Article < ApplicationRecord

  # default_scope { order(created_at: :desc) }

  has_rich_text :text

  validates_length_of :text, maximum: 25000

  belongs_to :user

  validates_presence_of :user

  has_many :users_articles
  has_many :liked_by_users, through: :users_articles, source: :user, dependent: :destroy

  has_many :comments, dependent: :destroy

  validates :title, presence: true

  visitable :ahoy_visit

  before_save :iframe, :thumb

  # Returns only articles created in the past 24 hours
  scope :daily, -> {
    where("created_at > ?", 1.day.ago)
  }

  # Returns a string .. Aricle title
  def name
    self.title
  end

  # Returns a string .. formatted Aricle created_at field
  def created
    if self.created_at > 1.day.ago
      "Today"
    elsif self.created_at > 1.week.ago
      "#{ActionController::Base.helpers.distance_of_time_in_words Time.now.to_date, self.created_at} ago"
    else
      "#{self.created_at.strftime('%b %-d, %Y')}"
    end
  end

  # Returns a string .. formatted Aricle updated_at field
  def updated
    if self.updated_at > 1.day.ago
      "Today"
    elsif self.updated_at > 1.week.ago
      "#{ActionController::Base.helpers.distance_of_time_in_words Time.now.to_date, self.updated_at} ago"
    else
      "#{self.updated_at.strftime('%b %-d, %Y')}"
    end
  end

  #show (before_save)
  # Returns a string (html_safe) .. iframe element from the embed string field
  def iframe
    if self.embed.present?
      ### YouTube
      ## Browser link --- use array to handle most playlist links, etc
      if self.embed =~ YOUTUBE_REGEX_ONE  # self.embed.include? 'https://www.youtube.com/watch?v='
        ("<iframe src='https://www.youtube.com/embed/#{self.embed[32..42]}' loading='lazy' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>").html_safe
      ## YouTube share link --- using array, because .split('https://youtu.be/').last wouldn't handle start at option ()?t=12)
      elsif self.embed =~ YOUTUBE_REGEX_TWO  # self.embed.include? 'https://youtu.be/'
        ("<iframe src='https://www.youtube.com/embed/#{self.embed[17..27]}' loading='lazy' frameborder='0' allow='accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture' allowfullscreen></iframe>").html_safe
      ### Validate + Generate iframe for whatever other embeds you want to allow (Google Maps, Vimeo, etc)
      # elsif
      else
        self.embed = nil
      end
    end
  end

  #_articles (before_save)
  # Returns a string (html_safe) .. img element from the embed string field
  def thumb
    if self.embed.present?
      ### YouTube
      ## Each YouTube video has 4 generated images [ /0 .. /3 ]
      if self.embed =~ YOUTUBE_REGEX_ONE
        ("<img alt='Media' loading='lazy' class='card-img-top' src='https://img.youtube.com/vi/#{self.embed[32..42]}/0.jpg' />").html_safe
      elsif self.embed =~ YOUTUBE_REGEX_TWO
        ("<img alt='Media' loading='lazy' class='card-img-top' src='https://img.youtube.com/vi/#{self.embed[17..27]}/0.jpg' />").html_safe
      else
        self.embed = nil
      end
    end
  end

  # Returns a string .. strip out unknown characters, etc.. for text in word tree
  def strip_text_for_tree
    self.text
        .to_plain_text
        .downcase
        .gsub(/[^a-z0-9\s]/i, ' ')
        .gsub(/[^0-9A-Za-z]/, ' ')
        .gsub(STOP_WORD_REGEX, ' ')
  end

  # Returns a string .. strip out unknown characters, etc.. for title in word tree
  def strip_title_for_tree
    self.title
        .downcase
        .gsub(/[^a-z0-9\s]/i, ' ')
        .gsub(/[^0-9A-Za-z]/, ' ')
        .gsub(STOP_WORD_REGEX, ' ')
  end

  # Search
  def self.search(search)
    if search && search.length > 0
      select('articles.*, lower(articles.title)').
      joins("LEFT OUTER JOIN users ON users.id = articles.user_id").
        where("lower(articles.title) LIKE ? OR lower(users.email) LIKE ?",
          "%#{search.downcase}%",
          "%#{search.downcase}%").
        distinct
    else
      where(nil)
    end
  end

  # Returns an array .. class method: number of articles month over year
  def self.month_of_year_articles
           group_by_month_of_year(:created_at)
          .count
          .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    render json: @articles.order('created_at DESC')
  end

  def show
    render json: Article.find(params[:id])
  end

  def create
    @article.user = current_user #.id gives Fixnum instead of User
    respond_to do |format|
      if @article.save
        format.json { render json: @article, status: :created }
      else
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.json { render json: @article, status: :ok }
      else
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

    def article_params
      params.require(:article).permit(:user_id, :title, :text, :embed)
    end

end

app/controllers/articles/likes_controller.rb
class Articles::LikesController < ApplicationController

  def create
    article = Article.find(params[:article_id])

    current_user.users_articles.create(article: article)

    respond_to do |format|
      @article = Article.find(params[:article_id])
      @liked_article = UsersArticle.find_by(user: current_user, article: @article)
      format.js
    end
  end

  def destroy
    users_article = UsersArticle.find(params[:id])

    users_article.destroy

    respond_to do |format|
      @article = Article.find(params[:article_id])
      format.js
    end

    # # users_article = GlobalID::Locator.locate(params[:id])
    # users_article = GlobalID::Locator.locate_signed(params[:id])
    # users_article.destroy
    # redirect_to article_path(users_article.article_id), notice: "Article unliked"
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  include Trackable

  def index
    @articles = @articles.order('created_at DESC')
                         .search(filter)
                         .paginate(page: params[:page], per_page: 12)

    ahoy.track "Viewed Blog"
  end

  def show
    @article = Article.find(params[:id])

    @articles = Article.where(user_id: @article.user.id)
                       .where.not(id: @article.id)
                       .order('created_at DESC')
                       .paginate(page: params[:page], per_page: 3)

    @liked_article = UsersArticle.find_by(user: current_user, article: @article)

    ahoy.track "Viewed Article: #{@article.title}", article_id: @article.id
  end

  def new
  end

  def edit
  end

  def create
    @article.user = current_user #.id gives Fixnum instead of User
    respond_to do |format|
      if @article.save
        format.html { redirect_to article_path(@article), notice: 'Article was successfully created.' }
      else
        format.html { render action: 'new', status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_path(@article), notice: 'Article was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_path, notice: 'Article was successfully deleted.' }
    end
  end

  private

  def article_params
    params.require(:article).permit(:user_id, :title, :text, :embed)
  end

  def filter
    @filter = params[:q]
  end

end

app/views/articles/_articles.html.erb
<div class="album py-5 text-start">
  <div class="row">
    <% @articles.each do |article| %>
    <div class="col-lg-4">
      <div class="card mb-4 box-shadow shadow">
        <div class="ratio ratio-4x3">
          <% if article.embed.present? %>
            <%= link_to article.thumb, article_path(article) %>
          <% else %>
            <%= link_to image_tag("missing.svg", alt: 'No video', class: 'card-img-top'), article_path(article) %>
          <% end %>
        </div><!-- .ratio .ratio-4x3 -->
        <div class="card-body text-nowrap">
          <h5 class="card-text jumbotron-heading fw-bold">
            <%= link_to truncate(article.title), article_path(article), class: 'text-dark' %>
          </h5>
          <p class="card-text"><i class="bi bi-person-fill text-muted"></i> <%= link_to truncate(article.user.name), article.user, class: 'text-info fw-bold' %></p>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
              <%= link_to article_path(article) do %>
                <i class='bi bi-book text-dark me-3' data-bs-toggle="tooltip" data-bs-placement="bottom" title="View"></i>
              <% end %>
              <% if can? :manage, article %>
                <%= link_to edit_article_path(article) do %>
                  <i class='bi bi-pencil text-orange me-3' data-bs-toggle="tooltip" data-bs-placement="bottom" title="Edit"></i>
                <% end %>
                <%= link_to article_path(article), method: :delete, data: { confirm: 'Are you sure you want to delete this article?' } do %>
                  <i class='bi bi-trash text-danger' data-bs-toggle="tooltip" data-bs-placement="bottom" title="Delete"></i>
                <% end %>
              <% end %>
            </div><!-- .btn-group -->
            <span>
              <small class="d-inline text-muted">
                <%= article.created %>
              </small>
              <% if article.users_articles.find_by(user_id: current_user) %>
                <i class="bi bi-heart-fill small ms-2 font-italic fw-bold text-tayberry"></i>
                <sup class="font-italic fw-bold text-tayberry"><%= article.liked_by_users.size %></sup>
              <% else %>
                <i class="bi bi-heart small ms-2 font-italic fw-light text-tayberry"></i>
                <sup class="font-italic text-tayberry"><%= article.liked_by_users.size %></sup>
              <% end %>
            </span>
          </div><!-- .d-flex -->
        </div><!-- .card-body -->
      </div><!-- .card .box-shadow .shadow -->
    </div><!-- .col-lg-4 -->
    <% end %>
  </div><!-- .row -->
  <div class="pagination">
    <%= will_paginate @articles,
      previous_label:'Prev',
      next_label:'Next',
      inner_window: 1, outer_window: -1
    %>
  </div><!-- .pagination -->
</div><!-- .album -->

app/views/articles/_form.html.erb
<%= form_for @article, html: { class: 'form-horizontal' } do |f| %>

  <% if @article.errors.any? %>
    <div class="position-fixed d-flex justify-content-center align-items-center z-eleven">
      <div class="toast show rounded toast-danger" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-header">
          <%= link_to root_path, class: 'navbar-brand' do %>
            <%= image_tag 'logo.png', alt: 'Logo', title: 'Home', class: 'footer-logo' %>
          <% end %>
          <strong class="me-auto"></strong>
          <small><%= Time.now.in_time_zone(current_user.timezone).strftime('%l:%M%P') %></small>
          <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
        <% @article.errors.full_messages.each do |msg| %>
          <div class="toast-body text-danger">
            <%= msg %>
          </div>
        <% end %>
      </div><!-- .toast .show -->
    </div><!-- .position-fixed .d-flex -->
  <% end %>

  <section class="mt-5 pb-5">
    <div class="row">
      <div class="col-lg-6 pt-1">
        <div class="form-floating mt-5 mb-5">
          <%= f.text_field :title, autocomplete: "Title", id: "inputTitle", class: "form-control", placeholder: "Title", autofocus: false %>
          <label for="inputTitle"><code class="text-orange">&#42; Title</code></label>
        </div><!-- .form-floating -->
        <div class="form-floating mt-5">
          <%= f.text_field :embed, autocomplete: "Embed", id: "inputEmbed", class: "form-control", placeholder: "Embed", autofocus: false %>
          <label for="inputEmbed" class="text-muted">
            YouTube Video URL
          </label>
        </div><!-- .form-floating -->
      </div><!-- .col-lg-6 .pt-1 -->
      <div class="col-lg-6">
        <div class="preview-thumb container mt-5 text-center shadow">
          <% if @article.embed.present? %>
            <%= @article.thumb %>
          <% else %>
            <%= image_tag("missing.svg", alt: 'No video', class: 'card-img-top') %>
          <% end %>
          <small class="text-muted">
            <i class="bi bi-info-circle-fill pointer me-1" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight"></i>
            YouTube video preview image
          </small>
        </div><!-- .container .text-center .form-floating -->
      </div><!-- .col-lg-6 -->
    </div><!-- .row -->

    <div class="jumbotron form-group">
      <%= f.rich_text_area :text, class: 'form-control' %>
    </div><!-- .jumbotron .form-group -->

    <div class="form-group d-flex justify-content-center">
      <%= link_to 'Cancel', articles_path, class: 'btn btn-secondary align-self-center mx-1' %>
      <%= f.submit 'Submit', class: 'btn btn-orange align-self-center mx-1' %>
    </div><!-- .form-group -->
  </section><!-- .pb-5 -->

<% end %>

<div class="offcanvas offcanvas-end" data-bs-scroll="true" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <small id="offcanvasRightLabel">Example YouTube Links</small>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div><!-- .offcanvas-header -->
  <div class="offcanvas-body">
    <h5 class="pb-1 mt-1">Format 1</h5>
    <div class="text-muted">
      <p class="pb-3 mb-0 small lh-125 border-bottom border-gray">
        https://youtu.be/<strong>u75Zsl1ECPQ</strong>
      </p>
    </div>
    <h5 class="pb-1 mt-4">Format 2</h5>
    <div class="text-muted">
      <p class="pb-3 mb-0 small lh-125 border-bottom border-gray">
        https://www.youtube.com/watch?v=<strong>u75Zsl1ECPQ</strong>
      </p>
    </div>
    <h5 class="pb-1 mt-4">Format 3</h5>
    <div class="text-muted">
      <p class="pb-3 mb-0 small lh-125 border-bottom border-gray">
        https://www.youtube.com/watch?v=<strong>u75Zsl1ECPQ</strong>&list=PLu9lbDbw-S8zyBwu9_aA2nE-3QocgyzRE&index=4
      </p>
    </div>
    <p class="mt-5 pb-3">
      <small class="ms-1">
        <span class="text-orange">Note</span>:
        Preview image reflects saved &amp; formatted link
      </small>
    </p><!-- .mt-5 .pb-3 -->
  </div><!-- .offcanvas-body -->
  <div class="offcanvas-footer text-end">
    <button type="button" class="btn btn-outline-secondary me-3 mb-3" data-bs-dismiss="offcanvas" aria-label="Close">Close</button>
  </div>
</div><!-- .offcanvas -->

app/views/articles/_like.html.erb
<%= link_to article_likes_path(@article), method: :post, remote: true do %>
  <i class="bi bi-heart lead font-italic text-tayberry" title="Like"></i>
<% end %> <sup class="font-italic text-tayberry" title="Like"><%= @article.liked_by_users.size %></sup>

app/views/articles/_search.html.erb
<form action="<%= action %>" method="get">
  <%= search_field_tag 'q', @filter, class: 'form-control', placeholder: 'Filter articles...' %>
</form>

app/views/articles/_unlike.html.erb
<%= link_to article_like_path(@article, id: @liked_article.id), method: :delete, remote: true do %>
  <i class="bi bi-heart-fill lead font-italic text-tayberry" title="Liked"></i>
<% end %> <sup class="font-italic text-tayberry"><%= @article.liked_by_users.size %></sup>

app/views/articles/edit.html.erb
<%= render partial: 'articles/form' %>

<section class="jumbotron text-center mt-5">
  <p>
    <%= link_to 'Delete', @article, method: :delete, data: { confirm: 'Are you sure you want to delete this article?' }, class: 'btn btn-outline-danger' %>
  </p>
</section><!-- .jumbotron .text-center -->

app/views/articles/index.html.erb
<section class="jumbotron text-center mt-5">
  <div class="container">
    <h1 class="jumbotron-heading">Blog</h1>
    <p class="lead text-start text-muted">Create, Read, Update, &amp; Destroy your articles. Like, add comments and link to articles' users' profiles.</p>
    <div class="filter">
      <%= render partial: 'articles/search', locals: { action: articles_path, q: '' } %>
    </div><!-- .filter -->
  </div><!-- .container -->
</section><!-- .jumbotron -->

<%= render partial: 'articles/articles' %>

app/views/articles/new.html.erb
<%= render partial: 'articles/form' %>

app/views/articles/show.html.erb
<section class="jumbotron text-center mt-5">
  <div class="container">
    <%= render ShowCreditComponent.new(item: @article) %>
    <% if can? :manage, @article %>
      <p class="mt-0 mb-0">
        <%= link_to edit_article_path(@article), class: 'btn btn-outline-dark' do %>
          <i class='bi bi-pencil-fill text-orange' data-bs-toggle="tooltip" data-bs-placement="bottom" title="Edit"></i>
        <% end %>
        <%= link_to article_path(@article), class: 'btn btn-outline-dark', method: :delete, data: { confirm: 'Are you sure you want to delete this article?' } do %>
          <i class='bi bi-trash-fill text-danger' data-bs-toggle="tooltip" data-bs-placement="bottom" title="Delete"></i>
        <% end %>
      </p>
    <% end %>
  </div><!-- .container -->
</section><!-- .jumbotron -->

<div class="card-body">
  <% if @article.embed.present? %>
    <div class="ratio ratio-16x9">
      <%= @article.iframe %>
    </div><!-- .ratio-16x9 -->
  <% end %>
  <div class="card-text mt-3 mb-2">
    <%= @article.text if @article.text.present? %>
  </div>
  <h4 id="heart" class="jumbotron-heading text-end mt-3 me-5">
    <% if @liked_article %>
      <%= render partial: 'unlike' %>
    <% else %>
      <%= render partial: 'like' %>
    <% end %>
  </h4>
</div><!-- .card-body -->

<section class="mb-5">
  <button class="w-100 btn btn-lg btn-outline-orange my-5" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasInput" aria-controls="offcanvasInput">
    Comment
  </button>
  <div class="row">
    <div class="col-12 overflow-auto" id='comments'>
      <%= render partial: 'comments/comment' %>
    </div><!-- .col-12 -->
    <div class="col-12 overflow-auto">
      <div class="offcanvas offcanvas-top comment-top" data-bs-scroll="true" tabindex="-1" id="offcanvasInput" aria-labelledby="offcanvasInputLabel">
        <div class="offcanvas-body">
          <%= render partial: 'comments/form' %>
        </div>
      </div>
    </div><!-- .col-12 -->
  </div><!-- .row -->
</section><!-- .mb-5 -->

<section class="text-center">
  <% if @articles.present? %>
    <h4 class="jumbotron-heading pt-5 mb-0 text-gray-dark">More articles by <%= link_to truncate(@article.user.name), @article.user, class: "text-info" %></h4>
    <div class="pt-0 mt-0 mb-0">
      <%= render partial: 'articles/articles' %>
    </div><!-- .pt-0 .mt-0 .mb-0 -->
  <% else %>
    <!-- TODO: top articles -->
    <div class="pb-5"></div>
  <% end %>
</section><!-- .text-center -->