config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticate :user, -> (user) { user.has_role?(:sysadmin) } do
    mount PgHero::Engine, at: "pghero"
  end

  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  root 'pages#welcome'

  get 'pages/terms_and_conditions'
  get 'pages/privacy_policy'
  get 'pages/cookie_policy'
  get 'pages/sitemap'
  get 'pages/public_statistics'
  get 'pages/cheat_sheet'

  get 'sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

  resources :users, only: [:show, :destroy] do
    put :toggle_theme, on: :member
  end

  resources :superadmins, only: [:new, :create]
  get '/superadmins', to: 'superadmins#new'

  resources :admins, only: [:new, :create]
  get '/admins', to: 'admins#new'

  resources :members, only: [:new, :create]
  get '/members', to: 'members#new'

  resources :visitors, only: [:new, :create]
  get '/visitors', to: 'visitors#new'

  resources :rooms do
    resources :notes, only: [:new, :create]
  end

  resources :articles do
    resources :comments, only: [:create, :destroy]
    scope module: :articles do
      resources :likes, only: [:create, :destroy]
    end
  end

  resources :todo_items, only: [:index]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # Todo Items
      resources :todo_items, only: [:index, :show, :create, :update, :destroy]
      # Articles
      resources :articles, only: [:index, :show, :create, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
      end
      # Rooms
      resources :rooms, only: [:index, :show, :create, :update, :destroy]
      # Charts
      namespace :charts do
        ## Analytics
        get 'month_of_year-visits'
        get 'month_of_year_visit-events'
        get 'device-type'
        get 'os-type'
        get 'browser-type'
        get 'landing-pages'
        get 'visit-mapping'
        get 'visit-country'
        get 'visit-region'
        get 'visit-city'
        get 'month_of_year_viewed_welcome'
        get 'month_of_year_viewed_dashboard'
        get 'month_of_year_viewed_blog'
        get 'month_of_year_viewed_rooms'
        get 'month_of_year_viewed_list'
        get 'month_of_year_viewed_article'
        get 'month_of_year_viewed_room'
        get 'month_of_year_viewed_user'
        get 'month_of_year_viewed_terms'
        get 'month_of_year_viewed_privacy-policy'
        get 'month_of_year_viewed_cookies-policy'
        get 'month_of_year_viewed_sitemap'
        get 'month_of_year_viewed_cheat-sheet'
        get 'month_of_year_viewed_public-statistics'
        # Users
        get 'month_of_year-superadmins'
        get 'month_of_year-admins'
        get 'month_of_year-members'
        get 'month_of_year-visitors'
        get 'month_of_year-users'
        get 'free_member-roles'
        get 'user-themes'
        get 'user-timezones'
        # Articles
        get 'article-likes'
        get 'month_of_year_article-likes'
        get 'month_of_year-articles'
        get 'month_of_year_single_articles'
        get 'free_member-articles'
        # Rooms
        get 'month_of_year-rooms'
        get 'month_of_year_single_rooms'
        get 'chat-rooms'
        # Todo Items
        get 'complete_incomplete-todos'
        get 'complete_incomplete_single-todos'
        get 'month_of_year-todos'
        get 'month_of_year_single-todos'
      end
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :trackable

  # default_scope { order(created_at: :desc) }

  visitable :ahoy_visit
  has_many :visits, class_name: "Ahoy::Visit"

  has_many :todo_items, dependent: :destroy
  has_many :rooms, dependent: :destroy

  has_many :users_articles, dependent: :destroy
  has_many :liked_articles, through: :users_articles, source: :article

  has_many :articles, dependent: :destroy

  has_many :comments, dependent: :destroy

  has_many :notes, dependent: :destroy

  after_create :assign_default_role, :first_items

  broadcasts_to ->(user) { :users }, inserts_by: :prepend

  # Returns only users created in the past 24 hours
  scope :daily, -> {
    where("created_at > ?", 1.day.ago)
  }

  # Assigns the default role 'visitor' to a new user (after_create)
  def assign_default_role
    self.add_role(:visitor)
  end

  # Creates two ToDo items when a user is created (after_create)
  def first_items
    2.times do |i|
      self.todo_items.create(title: "Item #{i+1} for #{self.email}", complete: i % 3 == 0 ? true : false)
    end
  end

  # Search
  def self.search(search)
    if search && search.length > 0
      where("lower(email) LIKE ?", "%#{search.downcase}%")
    else
      where(nil)
    end
  end

  # Returns a datetime .. formatted created_at in the user's timezone
  def created
    self.created_at.in_time_zone("#{self.timezone}").strftime('%b %-d, %Y.  %l:%M %p')
  end

  # Returns a string .. rolify first role (sysadmins are also superadmins)
  def role
    if self.roles.present?
      "#{self.roles.first.name}"
    end
  end

  # Returns a string .. email address before @
  def name
    "#{self.email.split('@').first}"
  end

  # Returns a datetime .. formatted current_sign_in_at in the user's timezone
  def current_login
    if self.current_sign_in_at.present?
      self.current_sign_in_at.in_time_zone("#{self.timezone}").strftime('%b %-d, %Y.  %l:%M %p')
    end
  end

  # Returns a string .. landing_page from the .last visit
  def landing
    if self.visits.present?
      "#{self.visits.last.landing_page}"
    else
      ''
    end
  end

  # Returns a string .. referring_domain from second to .last visit .last(2)[0] for current_user
  def second_to_last_referring_domain
    if self.visits.present? && self.visits.count > 1
      "#{self.visits.second_to_last.referring_domain}"
    else
      last_referring_domain
    end
  end

  # Returns a string .. .last event of .last visit
  def last_page
    if self.visits.present?
      if self.visits.last.events.present?
        "#{self.visits.last.events.last.name}"
      else
        ''
      end
    end
  end

  # Returns a string .. second_to_last event of .last visit .last(2)[0] for current_user
  def second_to_last_page
    if self.visits.present?
      if self.visits.last.events.present? && self.visits.last.events.count > 1
        "#{self.visits.last.events.second_to_last.name}"
      else
        last_page
      end
    end
  end

  # Returns a string .. OS and browser of .last visit
  # Fallback -> device_type
  def tech
    if self.visits.present?
      if self.visits.last.os.present? && self.visits.last.browser.present?
        "#{self.visits.last.browser} on #{self.visits.last.os}"
      elsif self.visits.last.device_type.present? && self.visits.last.os.present?
        "#{self.visits.last.os} on #{self.visits.last.device_type}"
      elsif self.visits.last.device_type.present? && self.visits.last.browser.present?
        "#{self.visits.last.browser} on #{self.visits.last.device_type}"
      elsif self.visits.last.browser.present?
        "#{self.visits.last.browser}"
      elsif self.visits.last.os.present?
        "#{self.visits.last.os}"
      elsif self.visits.last.device_type.present?
        "#{self.visits.last.device_type}"
      else
        ''
      end
    end
  end

  # Returns a string .. city and country of .last visit
  # Fallbacks -> region, latitude and longitude
  def location
    if self.visits.present?
      if self.visits.last.city.present? && self.visits.last.country.present?
        "#{self.visits.last.city}, #{self.visits.last.country}"
      elsif self.visits.last.region.present? && self.visits.last.country.present?
        "#{self.visits.last.region}, #{self.visits.last.country}"
      elsif self.visits.last.city.present? && self.visits.last.region.present?
        "#{self.visits.last.city}, #{self.visits.last.region}"
      elsif self.visits.last.city.present?
        "#{self.visits.last.city}"
      elsif self.visits.last.region.present?
        "#{self.visits.last.region}"
      elsif self.visits.last.country.present?
        "#{self.visits.last.country}"
      elsif self.visits.last.latitude.present? && self.visits.last.longitude.present?
        "#{self.visits.last.latitude}, #{self.visits.last.longitude}"
      else
        ''
      end
    end
  end

  # Returns an integer .. number of articles the user currently likes
  def liked_by_count
    # UsersArticle.where(user: self).count
    self.liked_articles.count
  end

  # Returns an array .. number of ToDo items the user currently has month over year
  def todo_items_count
    self.todo_items
        .group_by_month_of_year(:created_at)
        .count
        .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

  # Returns an array .. number of articles the user currently has month over year
  def articles_count
    self.articles
        .group_by_month_of_year(:created_at)
        .count
        .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

  # Returns an array .. number of rooms the user currently has month over year
  def rooms_count
    self.rooms
        .group_by_month_of_year(:created_at)
        .count
        .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

  # Returns an array .. class method: number of users month over year
  def self.month_of_year_users
           group_by_month_of_year(:created_at)
          .count
          .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

  # Returns an array .. class method: number of users month over year with sysadmin role
  def self.month_of_year_sysadmins
           with_role(:sysadmin)
          .group_by_month_of_year(:created_at)
          .count
          .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

  # Returns an array .. class method: number of users month over year with superadmin role
  def self.month_of_year_superadmins
           with_role(:superadmin)
          .group_by_month_of_year(:created_at)
          .count
          .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

  # Returns an array .. class method: number of users month over year with admin role
  def self.month_of_year_admins
           with_role(:admin)
          .group_by_month_of_year(:created_at)
          .count
          .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

  # Returns an array .. class method: number of users month over year with member role
  def self.month_of_year_members
           with_role(:member)
          .group_by_month_of_year(:created_at)
          .count
          .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

  # Returns an array .. class method: number of users month over year with visitor role
  def self.month_of_year_visitors
           with_role(:visitor)
          .group_by_month_of_year(:created_at)
          .count
          .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user
  include Trackable

  def show
    @rooms = Room.where(user_id: @user.id)
                 .order('created_at DESC')
                 .paginate(page: params[:page], per_page: 4)

    @articles = Article.where(user_id: @user.id)
                       .order('created_at DESC')
                       .paginate(page: params[:page], per_page: 12)

    ahoy.track "Viewed User: #{@user.name}", view_user_id: @user.id
  end

  def toggle_theme
    @user.toggle!(:dark_theme)
    render json: { result: true }
  end

  def destroy
    if can? :manage, @user # Prevent inserted delete button as html from working
      @user.destroy
    else
      redirect_to authenticated_root_url, alert: 'You CANNOT delete a user other than yourself. If you want to delete your account, please click on Edit Profile in the top menu.'
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

end

app/views/users/_charts.html.erb
<div class="col-lg-7">
  <div class="row mb-5">
    <div class="col-12 mt-3 text-start">
      <section class="mt-0">
        <div class="table-responsive">
          <table class="table table-hover table-striped">
            <tbody>
              <tr>
                <th>Role</th>
                <td><%= @user.role %></td>
              </tr>
              <tr>
                <th>Joined</th>
                <td><%= @user.created %></td>
              </tr>
              <tr>
                <th>Total Visits</th>
                <td><%= @user.visits.count %></td>
              </tr>
              <tr>
                <th>Total Logins</th>
                <td><%= @user.sign_in_count %></td>
              </tr>
              <tr>
                <th>Current Login</th>
                <td><%= @user.current_login %></td>
              </tr>
              <tr>
                <th>Landing Page</th>
                <td><%= link_to truncate(@user.landing), @user.landing, class: 'text-shnozberry' %></td>
              </tr>
              <tr>
                <th>Last Event</th>
                <td><%= @user == current_user ? @user.second_to_last_page : @user.last_page %></td>
              </tr>
              <tr>
                <th>Tech</th>
                <td><%= @user.tech %></td>
              </tr>
              <tr>
                <th>Location</th>
                <td><%= @user.location %></td>
              </tr>
              <tr>
                <th>Timezone</th>
                <td><%= @user.timezone %></td>
              </tr>
              <tr>
                <th>Dark Theme</th>
                <td><%= @user.dark_theme ? 'Yes' : 'No' %></td>
              </tr>
              <tr>
                <th>ToDo Items</th>
                <td><%= @user.todo_items.count %></td>
              </tr>
              <tr>
                <th>Articles</th>
                <td><%= @user.articles.count %></td>
              </tr>
              <tr>
                <th>Rooms</th>
                <td><%= @user.rooms.count %></td>
              </tr>
            </tbody>
          </table><!-- .table .table-striped -->
        </div><!-- .table-responsive -->
      </section><!-- .text-center mt-0 -->
    </div><!-- .col-12 -->
  </div><!-- .row .mb-5 -->
</div><!-- .col-lg-7 -->
<div class="col-lg-1 pb-1"></div>
<div class="col-lg-4">
  <p class="mt-2">
    <%= pie_chart ({"Not Complete" => @user.todo_items.where(complete: false).count,
                    "Complete" => @user.todo_items.where(complete: true).count}),
                    legend: false, download: {background: "#ffffff"}, colors: ["rgba(0,0,0,0.3)", "rgba(0,0,0,0.7)"], title: "List Status" %>
  </p>
  <p class="mt-0 mb-5">
    <%= area_chart @user.todo_items_count, download: {background: "rgba(0,0,0,0.5)"}, points: false, colors: ["rgba(0,0,0,0.5)"], title: "Items" %>
  </p>
</div><!-- .col-lg-4 -->

app/views/users/_rooms.html.erb
<%= turbo_stream_from :chats %>

<div class="table-responsive">
  <table class="table table-hover table-striped">
    <thead class="text-secondary fw-bold">
      <tr>
        <th scope="col">Room</th>
        <th scope="col">Created</th>
        <!-- <th scope="col"></th> -->
      </tr>
    </thead>
    <tbody>
      <% @rooms.each do |room| %>
        <tr>
          <td><%= link_to truncate(room.name), room, class: 'text-dark fw-bold' %></td>
          <td><%= room.created_at.in_time_zone("#{current_user.timezone}").strftime('%b %-d, %Y') %></td>
          <!-- <td class="text-end">
            <%# if can? :manage, room %>
              <%#= link_to room_path(room), method: :delete, data: { confirm: 'Are you sure you want to delete this room?' } do %>
                <i class="bi bi-trash text-dark me-1 pointer"></i>
              <%# end %>
            <%# end %>
          </td> -->
        </tr>
      <% end %>
    </tbody>
  </table><!-- .table .table-striped -->
</div><!-- .table-responsive -->
<div class="pagination">
  <%= will_paginate @rooms,
    previous_label:'Prev',
    next_label:'Next',
    inner_window: 1, outer_window: -1
  %>
</div><!-- .pagination -->

app/views/users/_search.html.erb
<form action="<%= users_path %>" method="get">
  <%= search_field_tag 'q', @filter, class: 'form-control', placeholder: 'Search users...' %>
</form>

app/views/users/_users.html.erb
<%= turbo_stream_from :users %>

<div class="table-responsive table-12">
  <table class="table table-hover table-striped">
    <thead class="text-secondary fw-bold">
      <tr>
        <th scope="col">User</th>
        <th scope="col">Role</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr id="<%= dom_id user %>">
          <td><%= link_to truncate(user.name), user, class: 'text-info' %></td>
          <td><%= user.role %></td>
          <td class="text-end">
            <% if can? :manage, user %>
              <%= link_to user_path(user), method: :delete, data: { confirm: 'Are you sure you want to delete this user?' } do %>
                <i class='bi bi-trash-fill text-muted me-2'></i>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table><!-- .table .table-striped -->
  <div class="pagination">
    <%= will_paginate @users,
      previous_label:'Prev',
      next_label:'Next',
      inner_window: 1, outer_window: -1
    %>
  </div><!-- .pagination -->
</div><!-- .table-responsive .table-12 -->

app/views/users/show.html.erb
<section class="jumbotron text-center mt-5">
  <div class="container">
    <h1 class="jumbotron-heading"><%= @user.name %></h1>
    <p class="lead">
      <% if can? :manage, @user  %>
        <%= mail_to @user.email, @user.email, class: 'text-info fw-bold' %>
      <% else %>
        🖖🏼
      <% end %>
    </p>
  </div><!-- .container -->
</section><!-- .jumbotron .text-center -->

<section class="text-center mt-0">
  <% if current_user.has_role?(:superadmin) %>
    <div class="row">
      <%= render partial: 'users/charts' %>
    </div><!-- .row -->
  <% end %>
  <% if !@user.has_role?(:visitor) && @user.rooms.count > 0 %>
    <div class="row mb-5">
      <div class="col-md-6">
        <p class="mt-0 mb-0">
          <%= line_chart @user.rooms_count, points: false, download: {background: "#ffffff"}, colors: ["rgba(0,0,0,0.9)"], title: "Rooms" %>
        </p>
      </div>
      <div class="col-md-6">
        <%= render partial: 'users/rooms' %>
      </div>
    </div><!-- .row -->
  <% end %>
  <div class="row mb-0">
    <div class="col-12">
      <p class="mt-2 mb-0">
        <%= line_chart @user.articles_count, points: false, download: {background: "#ffffff"}, colors: ["rgba(0,0,0,0.9)"], title: "Articles" %>
      </p>
    </div>
    <div class="col-12">
      <%= render partial: 'articles/articles' %>
    </div>
  </div><!-- .row -->
</section><!-- .text-center .mt-0 -->