config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticate :user, -> (user) { user.has_role?(:sysadmin) } do
    mount PgHero::Engine, at: "pghero"
  end

  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  root 'pages#welcome'

  get 'pages/terms_and_conditions'
  get 'pages/privacy_policy'
  get 'pages/cookie_policy'
  get 'pages/sitemap'
  get 'pages/public_statistics'
  get 'pages/cheat_sheet'

  get 'sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

  resources :users, only: [:show, :destroy] do
    put :toggle_theme, on: :member
  end

  resources :superadmins, only: [:new, :create]
  get '/superadmins', to: 'superadmins#new'

  resources :admins, only: [:new, :create]
  get '/admins', to: 'admins#new'

  resources :members, only: [:new, :create]
  get '/members', to: 'members#new'

  resources :visitors, only: [:new, :create]
  get '/visitors', to: 'visitors#new'

  resources :rooms do
    resources :notes, only: [:new, :create]
  end

  resources :articles do
    resources :comments, only: [:create, :destroy]
    scope module: :articles do
      resources :likes, only: [:create, :destroy]
    end
  end

  resources :todo_items, only: [:index]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # Todo Items
      resources :todo_items, only: [:index, :show, :create, :update, :destroy]
      # Articles
      resources :articles, only: [:index, :show, :create, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
      end
      # Rooms
      resources :rooms, only: [:index, :show, :create, :update, :destroy]
      # Charts
      namespace :charts do
        ## Analytics
        get 'month_of_year-visits'
        get 'month_of_year_visit-events'
        get 'device-type'
        get 'os-type'
        get 'browser-type'
        get 'landing-pages'
        get 'visit-mapping'
        get 'visit-country'
        get 'visit-region'
        get 'visit-city'
        get 'month_of_year_viewed_welcome'
        get 'month_of_year_viewed_dashboard'
        get 'month_of_year_viewed_blog'
        get 'month_of_year_viewed_rooms'
        get 'month_of_year_viewed_list'
        get 'month_of_year_viewed_article'
        get 'month_of_year_viewed_room'
        get 'month_of_year_viewed_user'
        get 'month_of_year_viewed_terms'
        get 'month_of_year_viewed_privacy-policy'
        get 'month_of_year_viewed_cookies-policy'
        get 'month_of_year_viewed_sitemap'
        get 'month_of_year_viewed_cheat-sheet'
        get 'month_of_year_viewed_public-statistics'
        # Users
        get 'month_of_year-superadmins'
        get 'month_of_year-admins'
        get 'month_of_year-members'
        get 'month_of_year-visitors'
        get 'month_of_year-users'
        get 'free_member-roles'
        get 'user-themes'
        get 'user-timezones'
        # Articles
        get 'article-likes'
        get 'month_of_year_article-likes'
        get 'month_of_year-articles'
        get 'month_of_year_single_articles'
        get 'free_member-articles'
        # Rooms
        get 'month_of_year-rooms'
        get 'month_of_year_single_rooms'
        get 'chat-rooms'
        # Todo Items
        get 'complete_incomplete-todos'
        get 'complete_incomplete_single-todos'
        get 'month_of_year-todos'
        get 'month_of_year_single-todos'
      end
    end
  end

end

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="position-fixed bottom-0 end-0 p-3 z-eleven">
    <div class="toast show border border-2 rounded <%= key == 'notice' ? 'toast-success border-success' : 'toast-danger border-danger' %>" role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag 'logo.png', alt: 'Logo', title: 'Home', class: 'footer-logo' %>
        <% end %>
        <strong class="me-auto"></strong>
        <small>
          <% if signed_in? %>
            <%= Time.now.in_time_zone(current_user.timezone).strftime('%l:%M%P') %>
          <% else %>
            <%= key.capitalize %>
          <% end %>
        </small>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>
      <div class="toast-body fw-bold <%= key == 'notice' ? 'text-success' : 'text-danger' %>">
        <%= value %>
      </div>
    </div><!-- .toast .show .border -->
  </div><!-- .position-fixed -->

  <!-- Alert flash at top of page -->
  <!-- <div class="container">
    <div class="d-flex justify-content-between alert <%#= key == 'notice' ? 'alert-primary' : 'alert-danger' %>" role="alert">
      <%#= value %>
      <button type="button" class="btn-close text-reset" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div> -->
<% end %>

app/views/shared/_footer.html.erb
<div class="footer-navbar bg-dark text-light mt-5">
  <footer class="container px-5 py-5">
    <div class="row">
      <div class="col-6 col-md">
        <h5>
          <i class="bi bi-journals me-1"></i>
          Legal
        </h5>
        <ul class="list-unstyled text-small">
          <li class="my-1">
            <%= link_to 'Privacy Policy', pages_privacy_policy_path, class: 'link-secondary' %>
          </li>
          <li class="my-1">
            <%= link_to 'Cookie Policy', pages_cookie_policy_path, class: 'link-secondary' %>
          </li>
          <li class="my-1">
            <%= link_to 'Terms', pages_terms_and_conditions_path, class: 'link-secondary' %>
          </li>
        </ul><!-- .list-unstyled .text-small -->
      </div><!-- .col-6 .col-md -->
      <div class="col-6 col-md">
        <h5>
          <i class="bi bi-emoji-wink me-1"></i>
          Social
        </h5>
        <ul class="list-unstyled text-small">
          <li class="my-1">
            <a href="https://github.com/TonyMaseda/" target= "_blank" class="link-secondary" title="Github">Github</a>
          </li>
          <li class="my-1">
            <a href="https://www.youtube.com/channel/UCTF8-ine9K2DPLfFV9UCzTQ" target= "_blank" class="link-secondary" title="Youtube">Youtube</a>
          </li>
          <li class="my-1">
            <a href="mailto:<%= ENV["GMAIL_USERNAME"] %>?subject=RRB Contact" class="link-secondary" title="Email">Email</a>
          </li>
        </ul><!-- .list-unstyled .text-small -->
      </div><!-- .col-6 .col-md -->
      <div class="col-6 col-md">
        <h5>
          <i class="bi bi-layers me-1"></i>
          About
        </h5>
        <ul class="list-unstyled text-small">
          <li class="my-1">
            <%= link_to 'Public Statistics', pages_public_statistics_path, data: { turbo: false }, class: 'link-secondary' %>
          </li>
          <li class="my-1">
            <%= link_to 'Site Map', pages_sitemap_path, class: 'link-secondary' %>
          </li>
        </ul><!-- .list-unstyled .text-small -->
      </div><!-- .col-6 .col-md -->
      <div class="col-6 col-md">
        <h5>
          <i class="bi bi-tsunami me-1"></i>
          Misc
        </h5>
        <ul class="list-unstyled text-small">
          <li class="my-1">
            <%= link_to 'Cheat Sheet', pages_cheat_sheet_path, class: 'link-secondary' %>
          </li>
        </ul><!-- .list-unstyled .text-small -->
      </div><!-- .col-6 .col-md -->
      <div class="col-12 col-md mt-5 text-end">
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag 'logo.png', alt: 'Logo', title: 'Home', class: 'footer-logo' %>
        <% end %>
        <small class="d-block mt-3">&copy; 2020 &#8211; <%= Time.current.year %></small>
        <small class="d-block mt-2">All Rights Reserved</small>
      </div><!-- .col-12 .col-md -->
    </div><!-- .row -->
  </footer><!-- .container .px-5 .py-5 -->
</div><!-- .bg-dark .text-light -->

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark position-fixed w-100 z-eleven p-0">
    <div class="container">
      <%= link_to root_path, data: { turbo: false }, class: 'navbar-brand text-decoration-none' do %>
        <%= image_tag 'logo.png', alt: 'Logo', class: 'header-logo bi pb-1 me-2', title: 'Home' %>
      <% end %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <!-- LEFT -->
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <% if user_signed_in? %>
            <li class="nav-item dropdown" title="Profile">
              <a class="<%= controller.class == UsersController ? 'active' : '' %> nav-link dropdown-toggle" href="#" id="dropdownUser" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="burger-icon bi bi-person"></i> <span class="burger-text">Profile</span></a>
              <div class="dropdown-menu shadow-lg" aria-labelledby="dropdownUser">
                <%= link_to(current_user, class: "dropdown-item") do %>
                  <span class="text-info"><%= current_user.name %></span>
                <% end %>
                <!-- Theme Toggle: markup -->
                <%= form_for(current_user, url: registration_path(current_user), html: { method: :put, class: "" }) do |f| %>
                  <div class="py-2 px-3 rounded-pill">
                    <div class="form-check form-switch">
                      <%= f.check_box :dark_theme, class: "form-check-input theme-toggle pointer", role: 'switch', data: {'user-id': current_user.id} %>
                      <small>Dark Theme</small>
                    </div>
                  </div>
                <% end %>
                <!-- Theme Toggle: script -->
                <script>
                  // console.log(document.cookie);
                  var element = document.body;
                  // Set Cookie
                  function setCookie(name,value,days) {
                    if (days) {
                      var date = new Date();
                      date.setTime(date.getTime()+(days*24*60*60*1000));
                      var expires = "; expires="+date.toGMTString();
                    }
                    else var expires = "";
                    document.cookie = name+"="+value+expires+"; path=/";
                  }
                  // Get Cookie
                  function getCookie(key) {
                    var keyValue = document.cookie.match('(^|;) ?' + key + '=([^;]*)(;|$)');
                    return keyValue ? keyValue[2] : null;
                    // console.log(getCookie('theme'));
                  }
                  // PUT toggle current_user dark_theme boolean
                  function toggleField() {
                    const csrf = document.querySelector("meta[name='csrf-token']").getAttribute("content");
                    fetch('/users/' + document.querySelector('.theme-toggle').getAttribute('data-user-id') + '/toggle_theme', {
                      method: 'PUT',
                      headers: {
                        'X-Requested-With': 'XMLHttpRequest',
                        'X-CSRF-Token': csrf
                      },
                    });
                  }
                  // Toggle Theme
                  document.querySelector(".theme-toggle").addEventListener('change', (e) => {
                    element.style.transition = "1s";
                    if (document.querySelector('.theme-toggle').checked == false) {
                      setCookie('theme','1', '30');
                      element.classList.remove("dark-mode");
                      toggleField();
                      // console.log('light(1) --  ' + getCookie('theme'));
                    } else {
                      setCookie('theme','2', '30');
                      element.classList.add("dark-mode");
                      toggleField();
                      // console.log('dark(2) -- ' + getCookie('theme'));
                    }
                  });
                  // Page Load
                  if (getCookie('theme') == 2) {
                    setCookie('theme','2', '30');
                    document.querySelector('.theme-toggle').checked = true;
                    element.classList.add("dark-mode");
                  } else { // == 1 OR null
                    document.querySelector('.theme-toggle').checked = false;
                  }
                </script>
                <%= link_to edit_user_registration_path, data: { turbo: false }, class: 'dropdown-item' do %>
                  Edit Profile
                <% end %>
                <%= link_to(destroy_user_session_path, method: :delete, data: { turbo: false }, class: "dropdown-item") do %>
                  Sign out
                <% end %>
              </div><!-- .dropdown-menu .shadow-lg -->
            </li><!-- .nav-item .dropdown -->
            <% if current_user.has_role?(:superadmin) %>
              <li class="nav-item dropdown" title="Users">
                <a class="<%= controller.class == SuperadminsController || AdminsController || MembersController || VisitorsController ? 'active' : '' %> nav-link dropdown-toggle" href="#" id="dropdownRole" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="burger-icon bi bi-people"></i> <span class="burger-text">Users</span></a>
                <div class="dropdown-menu shadow-lg" aria-labelledby="dropdownRole">
                  <%= link_to('/visitors', class: "dropdown-item") do %>
                    Free Users
                  <% end %>
                  <%= link_to('/members', class: "dropdown-item") do %>
                    Members
                  <% end %>
                  <%= link_to('/admins', class: "dropdown-item") do %>
                    Admins
                  <% end %>
                  <%= link_to('/superadmins', class: "dropdown-item") do %>
                    Super Admins
                  <% end %>
                </div><!-- .dropdown-menu .shadow-lg -->
              </li><!-- .nav-item .dropdown -->
            <% end %>
            <li class="nav-item dropdown" title="Blog">
              <a class="<%= controller.class == ArticlesController ? 'active' : '' %> nav-link dropdown-toggle" href="#" id="dropdownArticle" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="burger-icon bi bi-book"></i> <span class="burger-text">Blog</span></a>
              <div class="dropdown-menu shadow-lg" aria-labelledby="dropdownArticle">
                <%= link_to(articles_path, class: "dropdown-item") do %>
                  View Blog
                <% end %>
                <%# if user_signed_in? ## In event that authorize_user is removed ## %>
                  <%= link_to 'New Article', new_article_path, class: 'dropdown-item' %>
                <%# end %>
              </div><!-- .dropdown-menu .shadow-lg -->
            </li><!-- .nav-item .dropdown -->
            <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="bottom" title="ToDo List">
              <%= link_to(todo_items_path, class: "#{controller.class == TodoItemsController ? 'active' : ''} nav-link") do %>
                <i class="burger-icon bi bi-card-checklist"></i>
                <span class="burger-text">List</span>
              <% end %>
            </li><!-- .nav-item -->
            <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Chat">
              <%= link_to(rooms_path, data: { turbo: false }, class: "#{controller.class == RoomsController ? 'active' : ''} nav-link") do %>
                <i class="burger-icon bi bi-chat"></i>
                <span class="burger-text">Chat</span>
              <% end %>
            </li><!-- .nav-item .dropdown -->
          <% end %>
        </ul>
        <!-- RIGHT -->
        <% if user_signed_in? %>
          <form class="d-flex">
            <input class="form-control border-dark pt-1 pb-1 me-2 my-2" type="search" placeholder="Search" aria-label="Search">
            <!--
            <button class="btn btn-outline-transparent text-warning" type="submit">
              <i class="bi bi-search"></i>
            </button>
            -->
          </form>
        <% else %>
          <div class="d-flex mt-1 mb-2 welcome-nav-links">
            <%= link_to('Sign in', new_user_session_path, data: { turbo: false }, class: "nav-link text-white fw-bold border-0 rounded-1 p-2 me-1") %>
            <%= link_to('Sign up', new_user_registration_path, data: { turbo: false }, class: "nav-link btn bg-sign-in text-white fw-bold border-0 rounded-1 p-2") %>
          </div>
        <% end %>
      </div>
    </div>
  </nav>
</header>

app/views/shared/_modal.html.erb
<!-- Embed Format Instructions (avoid layout js issue with modal) -->
<div class="modal fade text-left" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModal" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLabel">
          Example YouTube Links
        </h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <i class="fas fa-window-close"></i>
        </button><!-- .close -->
      </div><!-- .modal-header -->
      <div class="modal-body">
        <div class="my-3 p-3 shadow-lg">
          <h5 class="border-bottom border-gray pb-1 mt-1">Format 1</h5>
          <div class="media text-muted pt-1">
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
              https://youtu.be/<strong>u75Zsl1ECPQ</strong>
            </p><!-- .media-body -->
          </div><!-- .media -->
          <h5 class="border-bottom border-gray pb-1 mt-4">Format 2</h5>
          <div class="media text-muted pt-1">
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
              https://www.youtube.com/watch?v=<strong>u75Zsl1ECPQ</strong>
            </p><!-- .media-body -->
          </div><!-- .media -->
          <h5 class="border-bottom border-gray pb-1 mt-4">Format 3</h5>
          <div class="media text-muted pt-1">
            <p class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
              https://www.youtube.com/watch?v=<strong>u75Zsl1ECPQ</strong>&list=PLu9lbDbw-S8zyBwu9_aA2nE-3QocgyzRE&index=4
            </p><!-- .media-body -->
          </div><!-- .media -->
        </div><!-- .my-3 .p-3 .shadow-lg -->
      </div><!-- .modal-body -->
    </div><!-- .modal-content -->
  </div><!-- .modal-dialog -->
</div><!-- .modal -->

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-5">
  <div class="container">
    <%= link_to "Rails React Bootstrap", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, method: :delete, class: "nav-link") %>
          <% else %>
            <%= link_to('Login', new_user_session_path, class: "nav-link") %>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>