config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  authenticate :user, -> (user) { user.has_role?(:sysadmin) } do
    mount PgHero::Engine, at: "pghero"
  end

  authenticated :user do
    root 'pages#dashboard', as: :authenticated_root
  end

  root 'pages#welcome'

  get 'pages/terms_and_conditions'
  get 'pages/privacy_policy'
  get 'pages/cookie_policy'
  get 'pages/sitemap'
  get 'pages/public_statistics'
  get 'pages/cheat_sheet'

  get 'sitemap.xml', to: 'sitemap#index', defaults: { format: 'xml' }

  resources :users, only: [:show, :destroy] do
    put :toggle_theme, on: :member
  end

  resources :superadmins, only: [:new, :create]
  get '/superadmins', to: 'superadmins#new'

  resources :admins, only: [:new, :create]
  get '/admins', to: 'admins#new'

  resources :members, only: [:new, :create]
  get '/members', to: 'members#new'

  resources :visitors, only: [:new, :create]
  get '/visitors', to: 'visitors#new'

  resources :rooms do
    resources :notes, only: [:new, :create]
  end

  resources :articles do
    resources :comments, only: [:create, :destroy]
    scope module: :articles do
      resources :likes, only: [:create, :destroy]
    end
  end

  resources :todo_items, only: [:index]

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      # Todo Items
      resources :todo_items, only: [:index, :show, :create, :update, :destroy]
      # Articles
      resources :articles, only: [:index, :show, :create, :update, :destroy] do
        resources :comments, only: [:create, :destroy]
      end
      # Rooms
      resources :rooms, only: [:index, :show, :create, :update, :destroy]
      # Charts
      namespace :charts do
        ## Analytics
        get 'month_of_year-visits'
        get 'month_of_year_visit-events'
        get 'device-type'
        get 'os-type'
        get 'browser-type'
        get 'landing-pages'
        get 'visit-mapping'
        get 'visit-country'
        get 'visit-region'
        get 'visit-city'
        get 'month_of_year_viewed_welcome'
        get 'month_of_year_viewed_dashboard'
        get 'month_of_year_viewed_blog'
        get 'month_of_year_viewed_rooms'
        get 'month_of_year_viewed_list'
        get 'month_of_year_viewed_article'
        get 'month_of_year_viewed_room'
        get 'month_of_year_viewed_user'
        get 'month_of_year_viewed_terms'
        get 'month_of_year_viewed_privacy-policy'
        get 'month_of_year_viewed_cookies-policy'
        get 'month_of_year_viewed_sitemap'
        get 'month_of_year_viewed_cheat-sheet'
        get 'month_of_year_viewed_public-statistics'
        # Users
        get 'month_of_year-superadmins'
        get 'month_of_year-admins'
        get 'month_of_year-members'
        get 'month_of_year-visitors'
        get 'month_of_year-users'
        get 'free_member-roles'
        get 'user-themes'
        get 'user-timezones'
        # Articles
        get 'article-likes'
        get 'month_of_year_article-likes'
        get 'month_of_year-articles'
        get 'month_of_year_single_articles'
        get 'free_member-articles'
        # Rooms
        get 'month_of_year-rooms'
        get 'month_of_year_single_rooms'
        get 'chat-rooms'
        # Todo Items
        get 'complete_incomplete-todos'
        get 'complete_incomplete_single-todos'
        get 'month_of_year-todos'
        get 'month_of_year_single-todos'
      end
    end
  end

end

app/models/room.rb
class Room < ApplicationRecord

  belongs_to :user

  has_many :notes, dependent: :destroy

  visitable :ahoy_visit

  validates_presence_of :user

  validates :name, presence: true

  broadcasts_to ->(room) { :rooms }, inserts_by: :prepend

  ## active_record callbacks ... rooms hotwire broadcast
  # broadcasts
  after_create_commit  { broadcast_prepend_to 'rooms' }
  after_update_commit  { broadcast_replace_to 'rooms' }
  after_destroy_commit { broadcast_remove_to 'rooms' }

  # active_record callback ... call set_room_key method before create
  before_create :set_room_key

  # Returns only rooms created in the past 24 hours
  scope :daily, -> {
    where("created_at > ?", 1.day.ago)
  }

  # Returns a string .. formatted Room created_at field
  def created
    if self.created_at > 1.day.ago
      "Today"
    elsif self.created_at > 1.week.ago
      "#{ActionController::Base.helpers.distance_of_time_in_words Time.now.to_date, self.created_at} ago"
    else
      "#{self.created_at.strftime('%b %-d, %Y')}"
    end
  end

  # Returns a string .. formatted Room updated_at field
  def updated
    if self.updated_at > 1.day.ago
      "Today"
    elsif self.updated_at > 1.week.ago
      "#{ActionController::Base.helpers.distance_of_time_in_words Time.now.to_date, self.updated_at} ago"
    else
      "#{self.updated_at.strftime('%b %-d, %Y')}"
    end
  end

  # Returns STUN and TURN server info from Twilio (before_create)
  def set_room_key
    require 'twilio-ruby'
    account_sid = ENV['TWILIO_ACCOUNT_SID']
    auth_token = ENV['TWILIO_AUTH_TOKEN']
    @client = Twilio::REST::Client.new(account_sid, auth_token)
    token = @client.tokens.create
    self.room_key = token.ice_servers
                         .to_json
                         .html_safe
  end

  # Returns a string .. strip out unknown characters, etc.. for title in word tree
  def strip_name_for_tree
    self.name
        .downcase
        .gsub(/[^a-z0-9\s]/i, ' ')
        .gsub(/[^0-9A-Za-z]/, ' ')
        .gsub(STOP_WORD_REGEX, ' ')
  end

  # Search
  def self.search(search)
    if search && search.length > 0
      select('rooms.*, lower(rooms.name)').
      joins("LEFT OUTER JOIN users ON users.id = rooms.user_id").
        where("lower(rooms.name) LIKE ? OR lower(users.email) LIKE ?",
          "%#{search.downcase}%",
          "%#{search.downcase}%").
        distinct
    else
      where(nil)
    end
  end

  # Returns an array .. class method: number of rooms month over year
  def self.month_of_year_rooms
           group_by_month_of_year(:created_at)
          .count
          .map{ |k, v| [I18n.t("date.month_names")[k], v] }
  end

end

app/controllers/api/v1/rooms_controller.rb
class Api::V1::RoomsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    render json: @rooms.order('created_at DESC')
  end

  def show
    render json: Room.find(params[:id])
  end

  def create
    @room.user = current_user #.id gives Fixnum instead of User
    respond_to do |format|
      if @room.save
        format.json { render json: @room, status: :created }
      else
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.json { render json: @room, status: :ok }
      else
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room.destroy
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

    def room_params
      params.require(:room).permit(:user_id, :name, :room_key)
    end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  include Trackable

  def index
    @rooms = @rooms.order('created_at DESC')
                   .search(filter)
                   .paginate(page: params[:page], per_page: 12)

    ahoy.track "Viewed Rooms"
  end

  def show
    @room = Room.find(params[:id])
    ahoy.track "Viewed Room: #{@room.name}", room_id: @room.id
  end

  def new
  end

  def edit
  end

  def create
    @room.user = current_user
    respond_to do |format|
      if @room.save
        format.html { redirect_to rooms_path }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @room.destroy
    # Remove block if you want to put delete button in partial (warden issue)
    respond_to do |format|
      format.html { redirect_to rooms_path, notice: 'Room was successfully deleted.' }
    end
  end

  private

  def room_params
    params.require(:room).permit(:user_id, :name, :room_key)
  end

  def filter
    @filter = params[:q]
  end

end

app/views/rooms/_form.html.erb
<%= turbo_frame_tag "room" do %>
  <%= form_for @room, html: { class: 'form-horizontal' } do |f| %>

    <% if @room.errors.any? %>
      <div class="position-fixed d-flex justify-content-center align-items-center z-eleven">
        <div class="toast show rounded toast-danger" role="alert" aria-live="assertive" aria-atomic="true">
          <div class="toast-header">
            <%= link_to root_path, class: 'navbar-brand' do %>
              <%= image_tag 'logo.png', alt: 'Logo', title: 'Home', class: 'footer-logo' %>
            <% end %>
            <strong class="me-auto"></strong>
            <small><%= Time.now.in_time_zone(current_user.timezone).strftime('%l:%M%P') %></small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <% @room.errors.full_messages.each do |msg| %>
            <div class="toast-body text-danger">
              <%= msg %>
            </div>
          <% end %>
        </div><!-- .toast .show -->
      </div><!-- .position-fixed .d-flex -->
    <% end %>

    <section class="pt-1 text-start">
      <div class="form-floating">
        <%= f.text_field :name, autocomplete: "Name", id: "inputName", class: "form-control", placeholder: "Name", autofocus: false %>
        <label for="inputEmail"><code class="text-tayberry">&#42; Name</code></label>
      </div><!-- .form-floating -->
      <div class="form-group d-flex justify-content-center">
        <%= link_to 'Cancel', @room, class: 'btn btn-secondary align-self-center mx-1' %>
        <%= f.submit 'Submit', class: 'btn btn-tayberry align-self-center mx-1' %>
      </div><!-- .form-group -->
    </section><!-- .pt-1 -->

  <% end %>
<% end # turbo_frame_tag "room" %>

app/views/rooms/_room.html.erb
<tr id="<%= dom_id room %>">
  <td>
    <%= link_to truncate(room.name), room, class: 'text-dark fw-bold' %>
  </td>
  <td>
    <%= room.created %>
  </td>
  <td>
    <%= link_to truncate(room.user.name), room.user, class: 'text-info fw-bold' %>
  </td>
  <!-- <td class="text-end">
    <%# if can? :manage, room %>
      <%#= link_to room_path(room), method: :delete, data: { confirm: 'Are you sure you want to delete this room?' } do %>
        <i class="bi bi-trash text-dark me-1 pointer"></i>
      <%# end %>
    <%# end %>
  </td>   -->
</tr>

app/views/rooms/_search.html.erb
<div class="row">
  <div class="col-lg-9 mt-1">
    <form action="<%= action %>" method="get">
      <%= search_field_tag 'q', @filter, class: 'form-control', placeholder: 'Filter rooms...' %>
    </form>
  </div><!-- .col-md-9 -->

  <div class="col-lg-3 mt-1 d-flex justify-content-center align-items-center">
    <div class="text-muted d-none d-lg-block" data-bs-toggle="offcanvas" data-bs-target="#offcanvasRight" aria-controls="offcanvasRight">
      <i class="bi bi-webcam me-1"></i> Webcam Issues?
    </div>
  </div><!-- .col-md-3 -->
</div><!-- .row -->


<div class="offcanvas offcanvas-end" data-bs-scroll="true" tabindex="-1" id="offcanvasRight" aria-labelledby="offcanvasRightLabel">
  <div class="offcanvas-header">
    <small id="offcanvasRightLabel">Webcam Issues</small>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div><!-- .offcanvas-header -->
  <div class="offcanvas-body">
    <h5 class="pb-1 mt-1">Windows</h5>
    <div class="text-muted">
      <p class="pb-3 mb-0 small lh-125 border-bottom border-gray">
        <a href="https://docs.microsoft.com/en-us/troubleshoot/browsers/disable-internet-explorer-windows" target="_blank">
          IEv6 needs to be turned off.
        </a>
      </p>
    </div>
    <h5 class="pb-1 mt-4">Firewall</h5>
    <div class="text-muted">
      <p class="pb-3 mb-0 small lh-125 border-bottom border-gray">
        <a href="https://www.makeuseof.com/tag/6-tips-on-how-to-unblock-a-webpage-from-behind-a-firewall/" target="_blank">
          You may need to add this url to the list of "allowed" websites by your firewall.
        </a>
      </p>
    </div>
  </div><!-- .offcanvas-body -->
  <div class="offcanvas-footer text-end">
    <button type="button" class="btn btn-outline-secondary me-3 mb-3" data-bs-dismiss="offcanvas" aria-label="Close">Close</button>
  </div>
</div><!-- .offcanvas -->

app/views/rooms/edit.html.erb
<%= render partial: 'rooms/form' %>

app/views/rooms/index.html.erb
<section class="jumbotron text-center mt-5">
  <div class="container">

    <%= turbo_frame_tag "room" do %>
      <h1 class="jumbotron-heading">Video Chat</h1>
      <p class="lead text-start text-muted">Interact with rooms via ActionCable. <i>If you're a member..</i> Create, Read, Update, &amp; Destroy WebRTC chat rooms (Hotwired).</p>
      <% if can? :manage, Room %>
        <p class="mt-2 mb-0">
          <%= link_to 'New Room', new_room_path, title: 'New Room', class: 'btn btn-outline-dark text-tayberry' %>
        </p>
      <% end %>
    <% end # turbo_frame_tag "room" %>

  </div><!-- .container -->
</section><!-- .jumbotron -->

<%= turbo_stream_from :rooms %>
<div class="filter mb-2">
  <%= render partial: 'rooms/search', locals: { action: rooms_path, q: '' } %>
</div><!-- .filter -->
<div class="table-responsive table-12">
  <table class="table table-hover table-striped">
    <thead class="text-secondary fw-bold">
      <tr>
        <th scope="col">Room</th>
        <th scope="col">Created</th>
        <th scope="col">By</th>
      </tr>
    </thead>
    <tbody id="rooms">
      <%= render partial: 'room', collection: @rooms %>
    </tbody><!-- #rooms (hotwired) -->
  </table><!-- .table .table-striped -->
  <div class="pagination">
    <%= will_paginate @rooms,
      previous_label:'Prev',
      next_label:'Next',
      inner_window: 1, outer_window: -1
    %>
  </div><!-- .pagination -->
</div><!-- .table-responsive .table-12 -->

app/views/rooms/new.html.erb
<%= render partial: 'rooms/form' %>

app/views/rooms/show.html.erb
<section class="jumbotron text-center mt-5">
  <div class="container">
    <%= turbo_frame_tag "room" do %>
      <%= render ShowCreditComponent.new(item: @room) %>
      <% if can? :manage, @room %>
        <p class="mt-0 mb-0">
          <%= link_to edit_room_path(@room), class: 'btn btn-outline-dark' do %>
            <i class='bi bi-pencil-fill text-tayberry' title="Edit"></i>
          <% end %>
          <%= link_to room_path(@room), class: 'btn btn-outline-dark', method: :delete, data: { confirm: 'Are you sure you want to delete this room?' } do %>
            <i class='bi bi-trash-fill text-danger' data-bs-toggle="tooltip" data-bs-placement="bottom" title="Delete"></i>
          <% end %>
        </p>
      <% end %>
    <% end # turbo_frame_tag "room" %>
  </div><!-- .container -->
</section><!-- .jumbotron -->

<section class="mb-5 pb-5">
  <div class='row'>
    <div class='col-12'>
      <div id='videos'
        data-controller='video-chat'
        data-video-chat-twilio='<%= @room.room_key %>'
        data-video-chat-session="<%= session.id %>"
        data-video-chat-id="<%= @room.id %>">
        <div class="d-inline" data-video-chat-target="remote_videos"></div>
        <video data-video-chat-target="local_video" autoplay></video>
      </div><!-- #videos -->
      <button class="w-100 btn btn-lg btn-outline-tayberry mb-2" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasInput" aria-controls="offcanvasInput">
        Add Notes
      </button>
    </div><!-- .col-12 -->
    <div class="col-12 overflow-auto" id='show-notes'>
      <div class="offcanvas offcanvas-top room-top" data-bs-scroll="true" tabindex="-1" id="offcanvasInput" aria-labelledby="offcanvasInputLabel">
        <div class="offcanvas-body">
          <%= turbo_frame_tag 'new_note', src: new_room_note_path(@room), target: :_top %>
        </div>
      </div>
      <%= turbo_stream_from @room %>
      <div id='notes'>
        <%= render @room.notes %>
      </div><!-- #notes -->
    </div><!-- .col-12 -->
  </div><!-- .row -->
</section><!-- .mb-5 .pb-5 -->